# Define the VAE hyperparameters
input_dim: 6           # Single input channel for CFD data (e.g., scalar fields like velocity magnitude)
out_dim: 6
embed_dim: 256          # Latent embedding dimension
patch_size: [4, 4, 4]  # Spatial patch size
overlap: 0.5            # Percentage of overlap of patches
spatial_heads: 
              encoder: 8       # Number of attention heads for spatial blocks
              decoder: 8       # Number of attention heads for spatial blocks
temporal_heads: 
              encoder: 8      # Number of attention heads for temporal blocks
              decoder: 8      # Number of attention heads for temporal blocks
mlp_dim: 512           # MLP hidden dimension
num_spatial_blocks: 4  # Number of spatial attention blocks
num_temporal_blocks: 4 # Number of temporal attention blocks
time_downsample: 5     # Temporal downsampling factor
latent_dim: 32         # Latent space dimension
scaler_type: revin
temporal_block_type: hybrid