# Default configuration
JOB_NAME="offline_sc3"
NODES=2
TASKS_PER_NODE=4
CPUS_PER_TASK=8
GPUS=4
TIME="6:00:00"
MEM="400000"
GLOBAL_BATCH_SIZE=256
BATCH_SIZE=8
EPOCHS=10
LR=1e-3
WEIGHT_DECAY=0.01
WARMUP_STEPS=1000
LIMIT_TRAIN_BATCHES=1024
MODEL="TFNO_t"
LOSS="one_step"
DATA_PATH="/leonardo_work/EUHPC_B20_015/HIT_LES_COMP/"
CASES="case1 case2 case3"
SEQ_LEN="2 2"
MODEL_CONFIG="TFNO_t_1.yaml"