# Default training configuration
TRAIN_JOB_NAME="online_sc2"
TRAIN_PARTITION="boost_usr_prod"
TRAIN_NODES=1
TRAIN_TIME="6:00:00"
TRAIN_TASKS_PER_NODE=4
TRAIN_CPUS_PER_TASK=8
TRAIN_GPUS=4
TRAIN_ACCOUNT="EUHPC_B20_015"
TRAIN_MEM="400000"
GLOBAL_BATCH_SIZE=256
BATCH_SIZE=8
STEPS=1024
LR=1e-3
WEIGHT_DECAY=0.01
WARMUP_STEPS=1000
MODEL="TFNO_t"
LOSS="one_step"
DATA_PATH="/leonardo_work/EUHPC_B20_015/HIT_LES_COMP/"
CASES="case1 case2 case3"
SEQ_LEN="2 2"
STREAM_PATH="./simulations/HIT/train_online_sc2"
RESERVOIR_SIZE=300
N_STREAMS=1
MODEL_CONFIG="TFNO_t_1.yaml"