# Default simulation configuration
SIM_JOB_NAME="simulation_sc5"
SIM_PARTITION="boost_usr_prod"
SIM_NODES=1
SIM_TIME="12:00:00"
SIM_NTASKS=1
SIM_CPUS_PER_TASK=8
SIM_GPUS=1
SIM_ACCOUNT="EUHPC_B20_015"
SIM_MEM="400000"
SIM_OUTPUT_DIR="train_online_sc5"
SIM_WAIT_TIME=5 